Security provider handling cleanups.
 * Do not remove BC provider after using it.  Removing "BC" can remove
   pre-installed or runtime-added BC provider by elsewhere and it causes
   unknown runtime error anywhere.  We avoid this.  To use part of
   jruby-openssl feature (X.509 and PKCS), users must be aware of dynamic BC
   provider adding.  (Fix for JRUBY_4535)

 * Reduce BC provider dependency.  Now Digest, Cipher, HMAC and PKey are
   BC provider free.  (Fix for JRUBY-4510)

 * Be crash-safe if BC provider is restricted by configuration.
   Features you can use without BC provider: Digest, Cipher, HMAC, PKey,
   Random and BN.  For such case, using following features causes
   GeneralSecurityException: SSL, X509, PKCS7, ASN1 and SPKI.

 * Be crash-safe even if BC jar is not on classpaths.  You cannot use
   features which depends on BC provider.  You cannot read/write PEM for PKey.

 * BC provider related implementation moves to OpenSSLReal.

 * added impl.Pkey.java for gathering PKey features which depends on BC.